Add --oplog parameter to mongodump
AlbertoPdRF/tisn.app pull request #343
Opened 2020-10-12 07:12 UTC by jacklagare

2020-10-12 08:27 UTC, AlbertoPdRF requested changes
Thanks for following up on #334 @jacklagare! 🧐

I'm afraid though that this as is won't work in production, as the `DB_URL` environment variable includes the database. Maybe we could do some string manipulation with it?

Also, I think that `lint-staged` is not working for you, you'll have to delete the `node_modules` folder and re-run `npm install` before committing again for the code style issues to get automatically fixed.

By the way, we have a Slack workspace that you can join if you want, so we can address small details quicker, you can find an invite link on the README!

And just for the record, this is related to #27.

2020-10-13 00:54 UTC, jacklagare commented
@AlbertoPdRF, I implemented parsing of the MongoDB URI. Kindly check.

2020-10-13 10:11 UTC, AlbertoPdRF commented
I'll test this out later today!

2020-10-13 11:51 UTC, AlbertoPdRF requested changes
I've left a few code suggestions, mostly about naming but also taking advantage of the new dependency to avoid crafting the URI manually.

Also, please note that there's a conflict left to resolve on the `package-lock.json` file.

I haven't yet tested this on a production-like environment, I'll do that as soon as I can and report the results back here!

2020-10-13 11:51 UTC, AlbertoPdRF commented on api/db/backup.js
> +const parser = require('mongodb-uri');
```suggestion
const mongodbUri = require('mongodb-uri');
```

2020-10-13 11:51 UTC, AlbertoPdRF commented on api/db/backup.js
> +  const mongoDbUrl = `${uri['scheme']}://${uri['username']}:${uri['password']}@${uri['hosts'][0]['host']}/`;
```suggestion
  // Remove database (and options) from URI to allow full database dumps
  const parsedUri = mongodbUri.parse(getDbUrl());
  delete parsedUri.database;
  delete parsedUri.options;
  const uri = mongodbUri.format(parsedUri);
```

2020-10-13 11:51 UTC, AlbertoPdRF commented on api/db/backup.js
> +  const dumpCmd = `mongodump --uri='${mongoDbUrl}' --gzip --archive='${dumpsPath}/${dumpFilename}' --oplog`;
```suggestion
  const dumpCmd = `mongodump --uri='${uri}' --gzip --archive='${dumpsPath}/${dumpFilename}' --oplog`;
```

2020-10-13 13:17 UTC, AlbertoPdRF commented on api/db/backup.js
> +const { parse } = require('path');
```suggestion
```
Oops, this line should go.

2020-10-13 13:19 UTC, jacklagare commented
Done. Those were awesome updates. I didn't know you can do that.

2020-10-13 15:44 UTC, AlbertoPdRF commented
Ok, I've now tested this and it works as expected! :tada: Thanks so much for addressing this @jacklagare!

Note: as mentioned on Slack, before merging this I'd like to get rid of the unrelated changes currently present on the `package-lock.json` file though. Let me know if you need help with that!

2020-10-14 06:42 UTC, AlbertoPdRF approved these changes
Looks clean now, thanks again for your work on this @jacklagare! 🙌

2020-10-14 06:43 UTC, merged